### ISSUE TITLE
服务器用不了了

### ISSUE THREAD

**Issue by dongpingy** [MZCretin/AutoUpdateProject#1]

**Comment by MZCretin** [comment]
测试包用的服务器是我公司测试服的服务器 出现用不了的情况应该是我们后台服务器在更新呢  过会再试试就好了

**Comment by MrZhangX** [comment]
问题是真的问题很大，连弹出框都不弹

**Comment by MZCretin** [comment]
既然已经投入使用 肯定是已经测试过一定机型的 你不提供你测试机的机型和集成说明  就下这种结论不妥吧

**Comment by MrZhangX** [comment]
这个问题是有个方法我们用不了，我感觉那里是写死的，不是自定义就能完成的

**Comment by MZCretin** [comment]
什么方法

**Comment by MrZhangX** [comment]
在基类的初始化中，那个model哪里的那个方法难道不是写死的？

**Comment by MZCretin** [comment]
不太清楚你想表达什么 你有什么需求？你是不希望按照我给出的格式返回数据吗还是怎样

**Comment by MrZhangX** [comment]
就是我的json数据和你的不一样，所以不希望按照你的格式，方法去做，所以说有问题

**Comment by MZCretin** [comment]
你找不到setTransition方法是因为你用错了版本 setTransition是在最新的版本里面的

**Comment by MZCretin** [comment]
![default](https://user-images.githubusercontent.com/16283031/27423696-06431538-5765-11e7-9f7d-e299f995ebfd.png)
或者使用compile 'com.github.MZCretin:AutoUpdateProject:v1.1.3'
