### ISSUE TITLE
这个可以支持静默刷新吗？

### ISSUE THREAD

**Issue by ssl90** [MZCretin/AutoUpdateProject#18]

**Comment by MZCretin** [comment]
@ssl90 静默刷新指的是静默安装apk吗

**Comment by ssl90** [comment]
是的，静默下载和安装，下载成功后，不安装的话不允许继续使用

**Comment by MZCretin** [comment]
@ssl90 你这个不叫静默刷新，你这个应该叫做强制更新，提示一个阻断的更新对话框，下载更新之后才能使用，否则不能使用！

**Comment by MZCretin** [comment]
@ssl90 这个是支持的

**Comment by ssl90** [comment]
@MZCretin 可以支持静默下载吗？

**Comment by ssl90** [comment]
不弹出activity那种，我感觉这个挺好用的，但是看代码检查有更新会弹出activity，这个可以支持一下做个选项吗？

**Comment by MZCretin** [comment]
可以

**Comment by ssl90** [comment]
@MZCretin 有qq、微信等联系方式吗？我用的过程中遇到了一些问题想和您沟通一下

**Comment by MZCretin** [comment]
@ssl90 静默下载更新已经支持
