### ISSUE TITLE
下载地址是https的时候，下载不了，报错CertPathValidatorException

### ISSUE THREAD

**Issue by gemgao** [MZCretin/AutoUpdateProject#21]
E/【AppUpdateUtils】: 文件下载出错，异常信息为：java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by gemgao** [comment]
经过排查，找到了原因，是下载框架FileDownloader不支持hhttps，我扩展了一下，用okhttp更换了他的URLConnection，问题已经解决

**Comment by MZCretin** [comment]
可能是你的https的根证书是不被信任的，我这里试了https是可以正常下载的！可以提供一下下载链接试试吗？我这边好做个兼容版本支持 @gemgao

**Comment by gemgao** [comment]
> 可能是你的https的根证书是不被信任的，我这里试了https是可以正常下载的！可以提供一下下载链接试试吗？我这边好做个兼容版本支持 @gemgao

https://files.danglaoshi.info/app-danglaoshi-release_BaiduA_sign.apk
这个是链接，我已经兼容了，只不过用了okhttp，FileDownloader原生的URLconnection。如果你要用okhttp，可以回复我，我直接把代码贴上来

**Comment by MZCretin** [comment]
@gemgao 
新版本已经可以支持配置okhttp了，感谢您的意见
https://github.com/MZCretin/AutoUpdateProject#新版本说明

**Comment by gemgao** [comment]
> @gemgao
> 新版本已经可以支持配置okhttp了，感谢您的意见
> [https://github.com/MZCretin/AutoUpdateProject#新版本说明](https://github.com/MZCretin/AutoUpdateProject#%E6%96%B0%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)

看到了你更新的代码，很及时，在纠结要不要把我兼容的代码删除了，直接依赖你的，哈哈
