### ISSUE TITLE
怎么拿到dialog对象实例，然后自己手动在页面销毁的时候dismiss掉

### ISSUE THREAD

**Issue by zhangshaobo87** [MZCretin/AutoUpdateProject#22]
主动避免 android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4fe3219 is not valid; is your activity running? 这个问题

**Comment by MZCretin** [comment]
你用的是哪个版本？

**Comment by zhangshaobo87** [comment]
2.0.3

**Comment by MZCretin** [comment]
你是怎么操作的？我排查下，看下什么原因，其实更新页面不是对话框实现的 全部是Activity做的

**Comment by zhangshaobo87** [comment]
并不是必现的，很难复现，很小几率出现，我先自定义一个activity试试

**Comment by zhangshaobo87** [comment]
![image](https://user-images.githubusercontent.com/17812840/68454808-bff0b680-0234-11ea-801c-d19b84f6f22f.png)

就是这地方的dialog会导致出现问题

**Comment by MZCretin** [comment]
我排查下

**Comment by MZCretin** [comment]
已修复
https://github.com/MZCretin/AutoUpdateProject#%E6%96%B0%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
