### ISSUE TITLE
插件对https的支持能否做的更简单一点

### ISSUE THREAD

**Issue by kunlun122** [MZCretin/AutoUpdateProject#25]
1.插件目前要使用https，还必须要使用okhttp，我看原生的也是支持https，只不过要改下相关代码
![image](https://user-images.githubusercontent.com/16523425/70764653-26687780-1d93-11ea-8785-db6968c37c52.png)
2.插件对https的支持能否改成内置的，插件内部根据升级的url来判断使用http连接，还是https连接。使用起来就加便捷
3.文档介绍建议按照数据类型分开，目前各种配置是掺杂在一起的，做不到复制过来就能使用。

**Comment by MZCretin** [comment]
1、插件本身就是默认支持https的，不需要你做额外的操作，如果下载不了可能是你的https的根证书是不被信任的
2、文档已经更新

**Comment by kunlun122** [comment]
多谢回复！
我说就是支持不受信任的https证书，这个能改成内置不？
另外
1.在下载的ar包中，并没有包含OkHttp3Connection这个类，找了一圈才发现在demo的源码中。所以我适配https的走了弯路。
2..sslSocketFactory(SSLUtils.createSSLSocketFactory())这个方法被deprecated了
3.适配不受信任的https证书，用原生的也能实现吧。为啥非得集成okhttp
我有点强迫症，请见谅！

**Comment by MZCretin** [comment]
里面的下载框架用的是FileDownloader，拥有断点续传等等一些优势，但是它本身是不支持不受信任的https证书的，所以如果你需要强行兼容的话，就用下okhttp吧，现在项目不用okhttp的应该很少了吧

**Comment by kunlun122** [comment]
先凑合着用吧
