### ISSUE TITLE
请教下接口地址有什么要求吗？

### ISSUE THREAD

**Issue by gulullu** [MZCretin/AutoUpdateProject#26]
我这个两个接口都可以通过浏览器和 Postman 访问，但是写到项目里用来做更新接口就报错：

http://dms.shopoint.cn/posapp/appinfo.json

这个接口报 405

http://api.myjson.com/bins/yxvg0

这个接口报404

但是用你的 http://www.cretinzp.com/system/versioninfo
又能正常访问。

请问有什么玄机吗？百思不解

**Comment by MZCretin** [comment]
没有限制 只要能请求到数据都可以  可能是你们的接口做了什么限制
