### ISSUE TITLE
相同版本的apk只会下载一次，防止重复下载！但每次都会重新下载。

### ISSUE THREAD

**Issue by zhangsange** [MZCretin/AutoUpdateProject#27]
作者你好，相同版本的apk只会下载一次，防止重复下载！但实际情况是每次都会重新下载。也没找到设置的地方。还有能加自定义保存路径吗？谢谢作者

**Comment by MZCretin** [comment]
提供下你配置的参数，比如：
{

    "versionCode": 25,
    "isForceUpdate": 1,
    "preBaselineCode": 24,
    "versionName": "v2.3.1",
    "downurl": "http://jokesimg.cretinzp.com/apk/app-release_231_jiagu_sign.apk",
    "updateLog": "v2.3.1\r\n1、优化细节和体验，更加稳定\n2、引入大量优质用户\r\n3、修复已知bug\n4、风格修改",
    "size": "31338250",
    "hasAffectCodes": "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24"

}

**Comment by MZCretin** [comment]
@zhangsange
