### ISSUE TITLE
HttpURLConnection always uses POST 

### ISSUE THREAD

**Issue by jing-li-rocos** [MZCretin/AutoUpdateProject#29]
https://github.com/MZCretin/AutoUpdateProject/blob/a63187dfd2bf57acda641acb0c5a6cf044a971c8/cretinautoupdatelibrary/src/main/java/com/cretin/www/cretinautoupdatelibrary/net/HttpUtils.java#L185

This line of code would force HttpURLConnection to use the POST method all the time.

Here is the reference https://developer.android.com/reference/java/net/HttpURLConnection#http-methods

**Comment by MZCretin** [comment]
Thanks a bundle.It will be fixed in next version.😆

**Comment by MZCretin** [comment]
has fixed！
