### ISSUE TITLE
通过大小来判断是否要重新下载是否好？

### ISSUE THREAD

**Issue by ziyouxiaozi** [MZCretin/AutoUpdateProject#30]
通过判断本地已存在的安装包的大小来与服务器的安装包大小来判断是否要重新下载这样好吗？会不会因为计算的大小有差异而下载有问题呀？

**Comment by MZCretin** [comment]
额，一个文件的字节数到哪儿都是一样大的吧！再者如果说你配置的时候把大小配置错了，导致的结果也就是每次都会下载新的apk而且，也就是多费点流量而已，不会影响整体的升级功能！
