### ISSUE TITLE
有点意思

### ISSUE THREAD

**Issue by Bleach1** [MZCretin/AutoUpdateProject#32]
以Model的方式 使用 必须setProdVersionCode这个属性吗 不适用不好使？

**Comment by Bleach1** [comment]
还有就是UI适配的问题  变形了

**Comment by MZCretin** [comment]
@Bleach1 哪个UI变形了？

**Comment by Bleach1** [comment]
例如 TypeConfig.UI_THEME_A 这种垂直布局的 版本号就会一部分被遮挡
