### ISSUE TITLE
卡在0%

### ISSUE THREAD

**Issue by liuzhaokun86** [MZCretin/AutoUpdateProject#36]
一直卡在0% 不动了。

D/BitmapFactory: decodeResource getCachedBitmap ok
D/BitmapFactory: decodeResource getCachedBitmap ok
D/BitmapFactory: decodeResource getCachedBitmap ok
E/【AppUpdateUtils】: 文件正在下载中，进度为0%
E/【AppUpdateUtils】: 文件正在下载中，进度为0%
E/【AppUpdateUtils】: 文件正在下载中，进度为0%
I/chatty: uid=10266(com.cretin.www.autoupdateproject) identical 1 line

**Comment by MZCretin** [comment]
请检查apk下载路径是否可用
