### ISSUE TITLE
使用TypeConfig.METHOD_GET模式依然以POST方式请求json文件

### ISSUE THREAD

**Issue by sdfwds4** [MZCretin/AutoUpdateProject#38]
AutoUpdateProject: 2.0.4
compileSdkVersion: 28
minSdkVersion 19
模拟器Android: 5.1.1

使用配置请求链接的方式，让插件自己解析并实现更新，用TypeConfig.METHOD_GET模式，apache日志显示，AutoUpdateProject依然以POST方式请求json文件。

看代码，HttpUtils.java中的doGet方法并没有调用setRequestMethod，会不会是被默认成POST了。

**Comment by sdfwds4** [comment]
经过调试，找到问题原因了
https://blog.csdn.net/u010665691/article/details/45557737?utm_source=blogxgwz6

**Comment by MZCretin** [comment]
@sdfwds4 已修复，请在2.0.4之后的版本中体验
