### ISSUE TITLE
小米11文件下载失败

### ISSUE THREAD

**Issue by funnull** [MZCretin/AutoUpdateProject#42]
文件下载出错，异常信息为：Create parent directory failed, please make sure you have permission to create file or directory on the path: /storage/emulated/0/com.hs.beidou.quantitativ/apks

**Comment by KennyLeung** [comment]
在API 30 的模拟器上也出现此问题，提示信息也完全相同。

**Comment by KennyLeung** [comment]
找到一个临时的解决方法，在项目的 build.gradle 中设置 targetSdk 28 就可以正常运行在api29 和 api30中。估计作者说他的demo可以运行在 android 10中，就是这个原因吧。

**Comment by MZCretin** [comment]
已经升级到30 
最新版本已经解决了这个问题
