### ISSUE TITLE
setMethodType为TypeConfig.METHOD_GET，但服务器提示为POST

### ISSUE THREAD

**Issue by szdastone** [MZCretin/AutoUpdateProject#45]
查看了源码，HttpUtils中的HttpURLConnection并没有根据GET或POST来设置。
        // 设置运行输入
        httpURLConnection.setDoInput(true);
        // 设置运行输出
        httpURLConnection.setDoOutput(true);
导致到服务器为POST，这里应该只有POST才设置为true
只能下了源码修改了。。。

**Comment by MZCretin** [comment]
已修改
