### ISSUE TITLE
1.1.2无法更新        300 + 1.1.2.hashCode() % 12  =  300

### ISSUE THREAD

**Issue by jewool** [MZCretin/AutoUpdateProject#46]
[](url)
![QQ截图20220307204658](https://user-images.githubusercontent.com/11656935/157037466-26092f4d-d1ed-4e0f-91c5-ab9be44bbb51.png)
![QQ截图20220307204708](https://user-images.githubusercontent.com/11656935/157037498-d5e11dd8-39ba-4455-af9b-dd9aa51ff592.png)

漏了300的情况

**Comment by MZCretin** [comment]
已解决
