### ISSUE TITLE
JsonHelper的问题

### ISSUE THREAD

**Issue by changtuixiaopangdun** [MZCretin/AutoUpdateProject#5]
我下载了库之后 用jsonhelper来解析类  就是解析不出来 但是换了个fastjson库 就解析出来了
{"Content":{"versionCode":"18","isForceUpdate":"1","preBaselineCode":"0","versionName":"2.1.1","downurl":"http://120.24.5.102/Webconfig/frj01_211_jiagu_sign.apk","hasAffectCodes":"11|12|13|14|15|16|17","updateLog":"1、修复bug 2、完善部分功能点 3、系统升级，强制更新","size":"10291218"},"Status":200,"Message":"","IbReturnContent":false}

服务器的数据是这样的

**Comment by MZCretin** [comment]
不好意思，周末有点事，没有及时回复！
看了下你服务器的数据，你应该使用自定义的解析类来解析这个json串！
![bb3f7214-3700-48f8-affb-8281b130eb41](https://user-images.githubusercontent.com/16283031/29756226-d8697c3e-8bd4-11e7-8544-bbbbbe9da477.png)
下面是链接，请尝试使用自定义的Model类来解析自己的json串！
[Android App内部自动更新Library （最新） ](http://blog.csdn.net/u010998327/article/details/70586322)
