### ISSUE TITLE
7.0适配问题

### ISSUE THREAD

**Issue by w499927181** [MZCretin/AutoUpdateProject#6]
![image](https://user-images.githubusercontent.com/11864225/30539343-882d6330-9ca4-11e7-9875-3d3cdeb0a8a9.png)
7.0.0下载后安装出现了这个问题

**Comment by MZCretin** [comment]
安装的test.apk吗

**Comment by w499927181** [comment]
是自己的apk

**Comment by MZCretin** [comment]
我刚刚重新上传了个测试apk  之前的接口用不了   你下个最新的测试apk试下  对7.0是做了适配的

**Comment by w499927181** [comment]
![image](https://user-images.githubusercontent.com/11864225/30571833-d7b24d94-9d1c-11e7-86df-8d8f61547965.png)
是我自己的apk，下载是成功的，安装的时候出现的问题

**Comment by w499927181** [comment]
268行报空指针

**Comment by MZCretin** [comment]
![default](https://user-images.githubusercontent.com/16283031/30571954-802083e2-9d1d-11e7-929a-7d1cff35d751.png)
7.0适配的工作做了吗

**Comment by w499927181** [comment]
做了的

**Comment by w499927181** [comment]
![image](https://user-images.githubusercontent.com/11864225/30572322-71238932-9d1f-11e7-8580-fc1e193fad39.png)

**Comment by w499927181** [comment]
解决了，是因为我以前也用到了这个东西，android:authorities这里填错了，不好意思，谢谢
