### ISSUE TITLE
解析包时出现问题

### ISSUE THREAD

**Issue by dongguaren** [MZCretin/AutoUpdateProject#8]
你好，感谢你的库~
我下载了最新的demo，在小米4和魅族MX6上进行了尝试，均出现了“解析包时出现问题”。
请问如何解决呢？

**Comment by MZCretin** [comment]
你是自己编译生成的apk 还是使用的我提供的apk？

**Comment by yang96515328** [comment]
编译生成的apk，下载完成之后解析错误

**Comment by MZCretin** [comment]
安装我提供的apk可以运行吗
