### ISSUE TITLE
您好，在华为mete8.0系统点击立即更新没有反应！

### ISSUE THREAD

**Issue by benxiongbuben** [MZCretin/AutoUpdateProject#9]
第一次：
01-06 10:43:54.222 9068-9068/com.example.android.cy_android V/AudioManager: playSoundEffect   effectType: 0
01-06 10:43:54.253 9068-9068/com.example.android.cy_android W/System.err: java.lang.NumberFormatException: For input string: "null"
01-06 10:43:54.259 9068-9068/com.example.android.cy_android W/System.err:     at java.lang.Long.parseLong(Long.java:590)
01-06 10:43:54.260 9068-9068/com.example.android.cy_android W/System.err:     at java.lang.Long.parseLong(Long.java:632)
01-06 10:43:54.261 9068-9068/com.example.android.cy_android W/System.err:     at com.cretin.www.cretinautoupdatelibrary.utils.CretinAutoUpdateUtils.requestPermission(CretinAutoUpdateUtils.java:649)
01-06 10:43:54.262 9068-9068/com.example.android.cy_android W/System.err:     at com.cretin.www.cretinautoupdatelibrary.utils.CretinAutoUpdateUtils.startUpdate(CretinAutoUpdateUtils.java:741)
01-06 10:43:54.263 9068-9068/com.example.android.cy_android W/System.err:     at com.cretin.www.cretinautoupdatelibrary.utils.CretinAutoUpdateUtils$7.onClick(CretinAutoUpdateUtils.java:579)
01-06 10:43:54.264 9068-9068/com.example.android.cy_android W/System.err:     at android.view.View.performClick(View.java:6291)
01-06 10:43:54.265 9068-9068/com.example.android.cy_android W/System.err:     at android.view.View$PerformClick.run(View.java:24931)
01-06 10:43:54.266 9068-9068/com.example.android.cy_android W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
01-06 10:43:54.267 9068-9068/com.example.android.cy_android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:101)
01-06 10:43:54.268 9068-9068/com.example.android.cy_android W/System.err:     at android.os.Looper.loop(Looper.java:166)
01-06 10:43:54.269 9068-9068/com.example.android.cy_android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7396)
01-06 10:43:54.271 9068-9068/com.example.android.cy_android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-06 10:43:54.272 9068-9068/com.example.android.cy_android W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
01-06 10:43:54.273 9068-9068/com.example.android.cy_android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
01-06 10:43:54.292 9068-9146/com.example.android.cy_android W/libEGL: EGLNativeWindowType 0xb7c62008 disconnect failed
我以为是我数据的size返回的是null的原因，但是后来加上后Log:
01-06 11:14:07.722 30850-30850/com.example.android.cy_android I/hwaps: JNI_OnLoad
01-06 11:14:07.815 30850-30850/com.example.android.cy_android V/AudioManager: playSoundEffect   effectType: 0
01-06 11:14:07.856 30850-30909/com.example.android.cy_android W/libEGL: EGLNativeWindowType 0xc2918808 disconnect failed
01-06 11:14:07.905 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:08.413 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:08.488 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:08.604 30850-30861/com.example.android.cy_android I/zygote: Background concurrent copying GC freed 4404(494KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 5MB/11MB, paused 508us total 112.148ms
01-06 11:14:08.931 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:09.262 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:09.387 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:10.434 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:10.894 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:11.207 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:11.508 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:11.773 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:12.001 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
01-06 11:14:12.229 30850-30850/com.example.android.cy_android E/NotificationManager: notifyAsUser: tag=null, id=0, user=UserHandle{0}
请问下是什么问题了？？

**Comment by MZCretin** [comment]
目前没有支持Android8.0

**Comment by m897329202** [comment]
更新失败，解析包出错
